Repository kawinie/project-mentory, pull requests merged in 2021-03, with the labels that each got.

#68 User Authentication
  .gitignore
  lib/auth.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/connect/[provider]/[redirect].tsx
  pages/landing.tsx
  pages/login.tsx
  pages/signup.tsx
  redux/actions.ts
  redux/reducers.ts
  redux/store.ts
  services/strapi/config/server.js
  services/strapi/package-lock.json
Labels: enhancement

#69 Mentor listing redesign
  components/modules/MentorCard/components/AutoScrollText.tsx
  components/modules/MentorCard/components/LikeButton.tsx
  components/modules/MentorCard/components/ProfileImage.tsx
  components/modules/MentorCard/components/StatGroup.tsx
  components/modules/MentorCard/components/index.tsx
  components/modules/MentorCard/variants/Base.tsx
  components/modules/MentorCard/variants/Desktop.tsx
  components/modules/MentorCard/variants/Mobile.tsx
  components/modules/NavBar/NavBar.tsx
  components/pages/MentorListing/FilterSidebar/FilterSidebar.tsx
  components/pages/MentorListing/ImageDisplay/ImageDisplay.tsx
  components/pages/MentorListing/ImageDisplay/index.tsx
  components/pages/MentorListing/MentorCard/MentorCard.tsx
  components/pages/MentorListing/MentorCard/index.tsx
  components/pages/MentorListing/index.tsx
  components/units/List/List.tsx
  components/units/SearchBar/SearchBar.tsx
  models/Article.ts
  models/Mentor.ts
  models/Mentor.tsx
  models/index.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/articles.ts
  pages/api/mentors.ts
  pages/index.tsx
  pages/landing.tsx
  pages/mentor-listing.tsx
  public/fonts/open-sans-v18-latin-300.woff
  public/fonts/open-sans-v18-latin-300.woff2
  public/fonts/open-sans-v18-latin-600.woff
  public/fonts/open-sans-v18-latin-600.woff2
  public/fonts/open-sans-v18-latin-700.woff
  public/fonts/open-sans-v18-latin-700.woff2
  public/fonts/open-sans-v18-latin-800.woff
  public/fonts/open-sans-v18-latin-800.woff2
  public/fonts/open-sans-v18-latin-regular.woff
  public/fonts/open-sans-v18-latin-regular.woff2
  public/fonts/roboto-v20-latin-500.woff
  public/fonts/roboto-v20-latin-500.woff2
  public/fonts/roboto-v20-latin-700.woff
  public/fonts/roboto-v20-latin-700.woff2
  public/fonts/roboto-v20-latin-900.woff
  public/fonts/roboto-v20-latin-900.woff2
  public/fonts/roboto-v20-latin-regular.woff
  public/fonts/roboto-v20-latin-regular.woff2
  services/strapi/api/mentors/models/mentors.settings.json
  services/strapi/package-lock.json
  stories/List.stories.tsx
  theme/components/Button.tsx
  theme/components/Menu.tsx
  theme/components/Tag.tsx
  theme/fonts.tsx
  theme/index.ts
Labels: bug, clean, enhancement

#76 Added username to store from social account login service
  pages/connect/[provider]/[redirect].tsx
Labels: bug fix
