Repository kawinie/project-mentory, pull requests merged in 2021-02, with the labels that each got.

#52 Refactored mentor listing page
  .vscode/settings.json
  components/modules/MentorFilterSidebar/MentorFilterSidebar.tsx
  components/modules/MentorFilterSidebar/index.ts
  components/modules/NavBar/NavBar.tsx
  components/pages/MentorListing/FilterSidebar/FilterSidebar.tsx
  components/pages/MentorListing/FilterSidebar/index.ts
  components/pages/MentorListing/ImageDisplay/ImageDisplay.tsx
  components/pages/MentorListing/ImageDisplay/index.tsx
  components/pages/MentorListing/MentorCard/MentorCard.tsx
  components/pages/MentorListing/MentorCard/index.tsx
  components/pages/MentorListing/index.tsx
  pages/index.tsx
  pages/mentor-filter-sidebar.tsx
  pages/mentor-listing.tsx
  pages/mentor.tsx
Labels: clean

#53 Added search component and updated NavBar
  components/modules/NavBar/NavBar.tsx
  components/units/SearchBar/SearchBar.tsx
  components/units/SearchBar/index.ts
  pages/landing.tsx
Labels: clean, enhancement

#58 Added window media query support for safari <= 13
  hooks/useScreen.tsx
Labels: bug fix

#56 Integrated Strapi
  .eslintrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  services/strapi/.editorconfig
  services/strapi/.env.example
  services/strapi/.gitignore
  services/strapi/README.md
  services/strapi/api/.gitkeep
  services/strapi/api/mentors/config/routes.json
  services/strapi/api/mentors/controllers/mentors.js
  services/strapi/api/mentors/models/mentors.js
  services/strapi/api/mentors/models/mentors.settings.json
  services/strapi/api/mentors/services/mentors.js
  services/strapi/config/database.js
  services/strapi/config/functions/bootstrap.js
  services/strapi/config/functions/cron.js
  services/strapi/config/functions/responses/404.js
  services/strapi/config/server.js
  services/strapi/extensions/.gitkeep
  services/strapi/extensions/users-permissions/config/jwt.js
  services/strapi/favicon.ico
  services/strapi/package.json
  services/strapi/public/robots.txt
  services/strapi/public/uploads/.gitkeep
  services/strapi/yarn.lock
  tsconfig.json
  utils/apollo.ts
Labels: integration

#64 Card redesign
  .github/workflows/lint-build.yml
  @types/index.d.ts
  components/modules/MentorCard/MentorCard.tsx
  components/modules/MentorCard/components/index.tsx
  components/modules/MentorCard/index.tsx
  components/modules/MentorCard/variants/Base.tsx
  components/modules/MentorCard/variants/Desktop.tsx
  components/modules/MentorCard/variants/Mobile.tsx
  components/modules/NavBar/NavBar.tsx
  models/Mentor.tsx
  package-lock.json
  package.json
  pages/index.tsx
  public/images/bjarne.jpg
  tailwind.config.js
  theme/components/Button.tsx
  theme/index.ts
  utils/index.ts
Labels: enhancement
