Repository kawinie/project-mentory, pull requests merged in 2021-01, with the labels that each got.

#16 Integrated eslint-plugin-import
  .eslintrc.js
  @types/redux.d.ts
  @types/twin.d.ts
  components/units/Button/Button.tsx
  components/units/InputField/InputField.tsx
  docs/pull_request_template.md
  package-lock.json
  package.json
  pages/_app.tsx
  pages/login.tsx
  redux/reducers.ts
  redux/selectors.ts
  redux/store.ts
  stories/Button.stories.tsx
  stories/List.stories.tsx
  tsconfig.json
Labels: enhancement

#18 Integration chakra UI
  .babelrc.js
  .eslintrc.js
  .lintstagedrc.js
  .storybook/preview.js
  .vscode/settings.json
  @types/twin.d.ts
  components/units/Button/Button.tsx
  components/units/Button/index.ts
  components/units/index.ts
  hooks/index.ts
  hooks/useScreen.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/login.tsx
  postcss.config.js
  stories/Button.stories.tsx
  stories/List.stories.tsx
  tailwind.config.js
  theme/index.ts
  tsconfig.json
Labels: enhancement, integration

#27 Patched lintstage pr template
  .eslintrc.js
  .lintstagedrc.js
  docs/pull_request_template.md
Labels: bug-fix

#38 Removed structure folder
  components/structures/README.md
Labels: bug

#41 Sidebar
  components/modules/MentorFilterSidebar/MentorFilterSidebar.tsx
  pages/mentor-filter-sidebar.tsx
Labels: enhancement

#40 Sub navbar
  components/modules/NavBar/NavBar.tsx
  components/modules/NavBar/index.ts
  components/structures/README.md
  package-lock.json
  package.json
Labels: enhancement

#43 Feature listing
  .eslintrc.js
  components/modules/MentorFilterSidebar/MentorFilterSidebar.tsx
  components/modules/MentorFilterSidebar/index.ts
  components/modules/NavBar/NavBar.tsx
  components/modules/NavBar/index.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/mentor-filter-sidebar.tsx
  pages/mentor.tsx
  public/svg/avatar-0.svg
  public/svg/avatar-1.svg
  public/svg/avatar-10.svg
  public/svg/avatar-11.svg
  public/svg/avatar-12.svg
  public/svg/avatar-13.svg
  public/svg/avatar-14.svg
  public/svg/avatar-15.svg
  public/svg/avatar-2.svg
  public/svg/avatar-3.svg
  public/svg/avatar-4.svg
  public/svg/avatar-5.svg
  public/svg/avatar-6.svg
  public/svg/avatar-7.svg
  public/svg/avatar-8.svg
  public/svg/avatar-9.svg
  tailwind.config.js
  theme/fonts.tsx
  theme/index.ts
Labels: enhancement

#44 Feature landing
  pages/index.tsx
  pages/landing.tsx
  public/images/coding.png
Labels: enhancement

#34 Feature signup
  package-lock.json
  package.json
  pages/signup.tsx
  public/images/back.png
  public/images/facebook.png
  public/images/google.png
  public/images/linkedin.png
  public/images/twitter.png
  public/svg/facebook.svg
  public/svg/google.svg
  public/svg/linkedin.svg
  public/svg/twitter.svg
Labels: enhancement
